//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Settings/PuzzleAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Backend.Util.Input
{
    public partial class @PuzzleControl: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PuzzleControl()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PuzzleAction"",
    ""maps"": [
        {
            ""name"": ""Puzzle"",
            ""id"": ""b65371d0-aa87-4c76-9790-80ea25dcd16c"",
            ""actions"": [
                {
                    ""name"": ""Press"",
                    ""type"": ""Button"",
                    ""id"": ""baa3ab1a-ee36-43bd-a996-23c6e269c64f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""Value"",
                    ""id"": ""e69d2283-463a-4ee2-a7f8-719c5017c8bb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f7349ad8-cfaf-49cc-ba9b-0018a0d1cf5f"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2102ae2f-6b53-4e34-b262-b4c6ff773b40"",
                    ""path"": ""<Pointer>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Puzzle
            m_Puzzle = asset.FindActionMap("Puzzle", throwIfNotFound: true);
            m_Puzzle_Press = m_Puzzle.FindAction("Press", throwIfNotFound: true);
            m_Puzzle_Position = m_Puzzle.FindAction("Position", throwIfNotFound: true);
        }

        ~@PuzzleControl()
        {
            UnityEngine.Debug.Assert(!m_Puzzle.enabled, "This will cause a leak and performance issues, PuzzleControl.Puzzle.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Puzzle
        private readonly InputActionMap m_Puzzle;
        private List<IPuzzleActions> m_PuzzleActionsCallbackInterfaces = new List<IPuzzleActions>();
        private readonly InputAction m_Puzzle_Press;
        private readonly InputAction m_Puzzle_Position;
        public struct PuzzleActions
        {
            private @PuzzleControl m_Wrapper;
            public PuzzleActions(@PuzzleControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @Press => m_Wrapper.m_Puzzle_Press;
            public InputAction @Position => m_Wrapper.m_Puzzle_Position;
            public InputActionMap Get() { return m_Wrapper.m_Puzzle; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PuzzleActions set) { return set.Get(); }
            public void AddCallbacks(IPuzzleActions instance)
            {
                if (instance == null || m_Wrapper.m_PuzzleActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PuzzleActionsCallbackInterfaces.Add(instance);
                @Press.started += instance.OnPress;
                @Press.performed += instance.OnPress;
                @Press.canceled += instance.OnPress;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
            }

            private void UnregisterCallbacks(IPuzzleActions instance)
            {
                @Press.started -= instance.OnPress;
                @Press.performed -= instance.OnPress;
                @Press.canceled -= instance.OnPress;
                @Position.started -= instance.OnPosition;
                @Position.performed -= instance.OnPosition;
                @Position.canceled -= instance.OnPosition;
            }

            public void RemoveCallbacks(IPuzzleActions instance)
            {
                if (m_Wrapper.m_PuzzleActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPuzzleActions instance)
            {
                foreach (var item in m_Wrapper.m_PuzzleActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PuzzleActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PuzzleActions @Puzzle => new PuzzleActions(this);
        public interface IPuzzleActions
        {
            void OnPress(InputAction.CallbackContext context);
            void OnPosition(InputAction.CallbackContext context);
        }
    }
}
