//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Settings/PuzzleAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Backend.Util.Input
{
    public partial class @PuzzleControl: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PuzzleControl()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PuzzleAction"",
    ""maps"": [
        {
            ""name"": ""PuzzleAction"",
            ""id"": ""b65371d0-aa87-4c76-9790-80ea25dcd16c"",
            ""actions"": [
                {
                    ""name"": ""OnClick"",
                    ""type"": ""Button"",
                    ""id"": ""baa3ab1a-ee36-43bd-a996-23c6e269c64f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f7349ad8-cfaf-49cc-ba9b-0018a0d1cf5f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PuzzleAction
            m_PuzzleAction = asset.FindActionMap("PuzzleAction", throwIfNotFound: true);
            m_PuzzleAction_OnClick = m_PuzzleAction.FindAction("OnClick", throwIfNotFound: true);
        }

        ~@PuzzleControl()
        {
            UnityEngine.Debug.Assert(!m_PuzzleAction.enabled, "This will cause a leak and performance issues, PuzzleControl.PuzzleAction.Disable() has not been called.");
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PuzzleAction
        private readonly InputActionMap m_PuzzleAction;
        private List<IPuzzleActionActions> m_PuzzleActionActionsCallbackInterfaces = new List<IPuzzleActionActions>();
        private readonly InputAction m_PuzzleAction_OnClick;
        public struct PuzzleActionActions
        {
            private @PuzzleControl m_Wrapper;
            public PuzzleActionActions(@PuzzleControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @OnClick => m_Wrapper.m_PuzzleAction_OnClick;
            public InputActionMap Get() { return m_Wrapper.m_PuzzleAction; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PuzzleActionActions set) { return set.Get(); }
            public void AddCallbacks(IPuzzleActionActions instance)
            {
                if (instance == null || m_Wrapper.m_PuzzleActionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PuzzleActionActionsCallbackInterfaces.Add(instance);
                @OnClick.started += instance.OnOnClick;
                @OnClick.performed += instance.OnOnClick;
                @OnClick.canceled += instance.OnOnClick;
            }

            private void UnregisterCallbacks(IPuzzleActionActions instance)
            {
                @OnClick.started -= instance.OnOnClick;
                @OnClick.performed -= instance.OnOnClick;
                @OnClick.canceled -= instance.OnOnClick;
            }

            public void RemoveCallbacks(IPuzzleActionActions instance)
            {
                if (m_Wrapper.m_PuzzleActionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPuzzleActionActions instance)
            {
                foreach (var item in m_Wrapper.m_PuzzleActionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PuzzleActionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PuzzleActionActions @PuzzleAction => new PuzzleActionActions(this);
        public interface IPuzzleActionActions
        {
            void OnOnClick(InputAction.CallbackContext context);
        }
    }
}
